// cities.js
const Cities = [
    "Lahore,Pakistan",
    "Karachi,Pakistan",
    "Islamabad,Pakistan",
    "New York,United States",
    "Los Angeles,United States",
    "Chicago,United States",
    "Houston,United States",
    "Phoenix,United States",
    "Philadelphia,United States",
    "San Antonio,United States",
    "San Diego,United States",
    "Dallas,United States",
    "London,United Kingdom",
    "Manchester,United Kingdom",
    "Birmingham,United Kingdom",
    "Glasgow,United Kingdom",
    "Tokyo,Japan",
    "Osaka,Japan",
    "Kyoto,Japan",
    "Nagoya,Japan",
    "Paris,France",
    "Marseille,France",
    "Lyon,France",
    "Toulouse,France",
    "Nice,France",
    "Berlin,Germany",
    "Munich,Germany",
    "Frankfurt,Germany",
    "Hamburg,Germany",
    "Cologne,Germany",
    "Sydney,Australia",
    "Melbourne,Australia",
    "Brisbane,Australia",
    "Perth,Australia",
    "Toronto,Canada",
    "Vancouver,Canada",
    "Montreal,Canada",
    "Ottawa,Canada",
    "Calgary,Canada",
    "Beijing,China",
    "Shanghai,China",
    "Guangzhou,China",
    "Shenzhen,China",
    "Chengdu,China",
    "Moscow,Russia",
    "Saint Petersburg,Russia",
    "Novosibirsk,Russia",
    "Yekaterinburg,Russia",
    "Nizhny Novgorod,Russia",
    "Rio de Janeiro,Brazil",
    "São Paulo,Brazil",
    "Brasília,Brazil",
    "Salvador,Brazil",
    "Fortaleza,Brazil",
    "Mexico City,Mexico",
    "Guadalajara,Mexico",
    "Monterrey,Mexico",
    "Puebla,Mexico",
    "Tijuana,Mexico",
    "Cairo,Egypt",
    "Alexandria,Egypt",
    "Giza,Egypt",
    "Shubra El-Kheima,Egypt",
    "Port Said,Egypt",
    "Cape Town,South Africa",
    "Johannesburg,South Africa",
    "Durban,South Africa",
    "Pretoria,South Africa",
    "Port Elizabeth,South Africa",
    "Dubai,United Arab Emirates",
    "Abu Dhabi,United Arab Emirates",
    "Sharjah,United Arab Emirates",
    "Al Ain,United Arab Emirates",
    "Fujairah,United Arab Emirates",
    "Buenos Aires,Argentina",
    "Córdoba,Argentina",
    "Rosario,Argentina",
    "Mendoza,Argentina",
    "La Plata,Argentina",
    "Istanbul,Turkey",
    "Ankara,Turkey",
    "Izmir,Turkey",
    "Bursa,Turkey",
    "Adana,Turkey",
    "Seoul,South Korea",
    "Busan,South Korea",
    "Incheon,South Korea",
    "Daegu,South Korea",
    "Daejeon,South Korea",
    "Bangkok,Thailand",
    "Chiang Mai,Thailand",
    "Phuket,Thailand",
    "Pattaya,Thailand",
    "Udon Thani,Thailand",
    "Rome,Italy",
    "Milan,Italy",
    "Naples,Italy",
    "Turin,Italy",
    "Palermo,Italy",
  ];
  
  export default Cities;
  